[package]
name = "romodoro"
version = "0.1.0"
authors = ["michaelfletcher"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
clap = "2.32.0"
termion = "1.5.1"
ctrlc = "3.1.1"

[profile.release]
lto = true